
# DO NOT DELETE: Beginning of Haskell dependencies
BuiltinInstances.o : BuiltinInstances.lhs
BuiltinInstances.o : ./Env.hi
BuiltinInstances.o : ./Functorise.hi
BuiltinInstances.o : ./Grammar.hi
BuiltinInstances.o : ./Folding.hi
BuiltinInstances.o : ./MonadLibrary.hi
BuiltinInstances.o : ./MyPrelude.hi
BuiltinInstances.o : ./StartTBasis.hi
BuiltinInstances.o : ./PrettyPrinter.hi
Chase.o : Chase.lhs
CommandLine.o : CommandLine.lhs
CommandLine.o : ./NonStdTrace.hi
DependencyAnalysis.o : DependencyAnalysis.lhs
DependencyAnalysis.o : ./Env.hi
DependencyAnalysis.o : ./Folding.hi
DependencyAnalysis.o : ./Grammar.hi
DependencyAnalysis.o : ./GraphLibrary.hi
DependencyAnalysis.o : ./MyPrelude.hi
DependencyAnalysis.o : ./PrettyPrinter.hi
DependencyAnalysis.o : ./TypeBasis.hi
Env.o : Env.lhs
Env.o : ./MyPrelude.hi
Env.o : ./MonadLibrary.hi
Flags.o : Flags.lhs
Flags.o : ./CommandLine.hi
Folding.o : Folding.lhs
Folding.o : ./Grammar.hi
Folding.o : ./MyPrelude.hi
Folding.o : ./MonadLibrary.hi
Folding.o : ./PrettyPrinter.hi
FunctorNames.o : FunctorNames.lhs
FunctorNames.o : ./MonadLibrary.hi
FunctorNames.o : ./MyPrelude.hi
FunctorNames.o : ./Grammar.hi
FunctorNames.o : ./PrettyPrinter.hi
Functorise.o : Functorise.lhs
Functorise.o : ./Grammar.hi
Functorise.o : ./MyPrelude.hi
Functorise.o : ./Folding.hi
Functorise.o : ./MonadLibrary.hi
Grammar.o : Grammar.lhs
Grammar.o : ./MyPrelude.hi
GraphLibrary.o : GraphLibrary.lhs
GraphLibrary.o : ./MyPrelude.hi
GraphLibrary.o : ./StateFix.hi
InferKind.o : InferKind.lhs
InferKind.o : ./Functorise.hi
InferKind.o : ./MyPrelude.hi
InferKind.o : ./Grammar.hi
InferKind.o : ./TypeGraph.hi
InferKind.o : ./TypeBasis.hi
InferKind.o : ./StateFix.hi
InferKind.o : ./Env.hi
InferKind.o : ./PrettyPrinter.hi
InferKind.o : ./UnifyTypes.hi
InferKind.o : ./MonadLibrary.hi
InferType.o : InferType.lhs
InferType.o : ./UnifyTypes.hi
InferType.o : ./TypeGraph.hi
InferType.o : ./TypeBasis.hi
InferType.o : ./Env.hi
InferType.o : ./MyPrelude.hi
InferType.o : ./MonadLibrary.hi
InferType.o : ./StateFix.hi
InferType.o : ./Grammar.hi
InferType.o : ./ParseLibrary.hi
InferType.o : ./Parser.hi
InferType.o : ./PrettyPrinter.hi
LabelType.o : LabelType.lhs
LabelType.o : ./Folding.hi
LabelType.o : ./Grammar.hi
LabelType.o : ./InferKind.hi
LabelType.o : ./InferType.hi
LabelType.o : ./MonadLibrary.hi
LabelType.o : ./MyPrelude.hi
LabelType.o : ./StartTBasis.hi
LabelType.o : ./StartTBasis.hi
LabelType.o : ./StateFix.hi
LabelType.o : ./TypeBasis.hi
LabelType.o : ./TypeGraph.hi
LabelType.o : ./UnifyTypes.hi
Main.o : Main.lhs
Main.o : ./DependencyAnalysis.hi
Main.o : ./Grammar.hi
Main.o : ./LabelType.hi
Main.o : ./MonadLibrary.hi
Main.o : ./MyPrelude.hi
Main.o : ./Parser.hi
Main.o : ./PolyInstance.hi
Main.o : ./PrettyPrinter.hi
Main.o : ./StateFix.hi
Main.o : ./TypeBasis.hi
Main.o : ./Flags.hi
MonadLibrary.o : MonadLibrary.lhs
MonadLibrary.o : ./StateFix.hi
MonadLibrary.o : ./MyPrelude.hi
MyPrelude.o : MyPrelude.lhs
MyPrelude.o : ./NonStdTrace.hi
MyPrelude.o : ./Flags.hi
NonStdTrace.o : NonStdTrace.lhs
ParseLibrary.o : ParseLibrary.lhs
ParseLibrary.o : ./MonadLibrary.hi
ParseLibrary.o : ./MyPrelude.hi
Parser.o : Parser.lhs
Parser.o : ./MyPrelude.hi
Parser.o : ./MonadLibrary.hi
Parser.o : ./ParseLibrary.hi
Parser.o : ./Grammar.hi
PolyInstance.o : PolyInstance.lhs
PolyInstance.o : ./Env.hi
PolyInstance.o : ./Grammar.hi
PolyInstance.o : ./Folding.hi
PolyInstance.o : ./Functorise.hi
PolyInstance.o : ./FunctorNames.hi
PolyInstance.o : ./BuiltinInstances.hi
PolyInstance.o : ./TypeGraph.hi
PolyInstance.o : ./TypeBasis.hi
PolyInstance.o : ./InferType.hi
PolyInstance.o : ./MonadLibrary.hi
PolyInstance.o : ./MyPrelude.hi
PolyInstance.o : ./PrettyPrinter.hi
PolyInstance.o : ./StartTBasis.hi
PolyInstance.o : ./TypeBasis.hi
PolyInstance.o : ./Flags.hi
PrettyPrintExtra.o : PrettyPrintExtra.lhs
PrettyPrintExtra.o : ./PrettyPrintLibrary.hi
PrettyPrintLibrary.o : PrettyPrintLibrary.lhs
PrettyPrinter.o : PrettyPrinter.lhs
PrettyPrinter.o : ./PrettyPrintExtra.hi
PrettyPrinter.o : ./Grammar.hi
StartTBasis.o : StartTBasis.lhs
StartTBasis.o : ./Parser.hi
StartTBasis.o : ./ParseLibrary.hi
StartTBasis.o : ./MyPrelude.hi
StartTBasis.o : ./Grammar.hi
StartTBasis.o : ./MonadLibrary.hi
StartTBasis.o : ./TypeBasis.hi
StartTBasis.o : ./InferKind.hi
StartTBasis.o : ./NonStdTrace.hi
StartTBasis.o : ./Flags.hi
StateFix.o : StateFix.lhs
TypeBasis.o : TypeBasis.lhs
TypeBasis.o : ./Grammar.hi
TypeBasis.o : ./Folding.hi
TypeBasis.o : ./Functorise.hi
TypeBasis.o : ./MyPrelude.hi
TypeBasis.o : ./MonadLibrary.hi
TypeBasis.o : ./Env.hi
TypeBasis.o : ./TypeGraph.hi
TypeError.o : TypeError.lhs
TypeError.o : ./TypeGraph.hi
TypeError.o : ./MonadLibrary.hi
TypeError.o : ./PrettyPrinter.hi
TypeError.o : ./Grammar.hi
TypeGraph.o : TypeGraph.lhs
TypeGraph.o : ./MyPrelude.hi
TypeGraph.o : ./Grammar.hi
TypeGraph.o : ./PrettyPrinter.hi
TypeGraph.o : ./MonadLibrary.hi
TypeGraph.o : ./MyPrelude.hi
TypeGraph.o : ./Env.hi
TypeGraph.o : ./Folding.hi
TypeGraph.o : ./StateFix.hi
UnifyTypes.o : UnifyTypes.lhs
UnifyTypes.o : ./TypeGraph.hi
UnifyTypes.o : ./TypeError.hi
UnifyTypes.o : ./MonadLibrary.hi
UnifyTypes.o : ./Env.hi
UnifyTypes.o : ./Grammar.hi
UnifyTypes.o : ./MyPrelude.hi
# DO NOT DELETE: End of Haskell dependencies
