# DO NOT DELETE: Beginning of Haskell dependencies
DependencyAnalysis.g_o : DependencyAnalysis.lhs
DependencyAnalysis.g_o : ./Env.g_hi
DependencyAnalysis.g_o : ./Folding.g_hi
DependencyAnalysis.g_o : ./Grammar.g_hi
DependencyAnalysis.g_o : ./GraphLibrary.g_hi
DependencyAnalysis.g_o : ./MyPrelude.g_hi
DependencyAnalysis.g_o : ./PrettyPrinter.g_hi
DependencyAnalysis.g_o : ./TypeBasis.g_hi
Env.g_o : Env.lhs
Env.g_o : ./MyPrelude.g_hi
Env.g_o : ./MonadLibrary.g_hi
Folding.g_o : Folding.lhs
Folding.g_o : ./Grammar.g_hi
Folding.g_o : ./MyPrelude.g_hi
Folding.g_o : ./MonadLibrary.g_hi
Functorize.g_o : Functorize.lhs
Functorize.g_o : ./Env.g_hi
Functorize.g_o : ./Grammar.g_hi
Functorize.g_o : ./MyPrelude.g_hi
Functorize.g_o : ./Parser.g_hi
Functorize.g_o : ./StartTBasis.g_hi
Grammar.g_o : Grammar.lhs
Grammar.g_o : ./MyPrelude.g_hi
GraphLibrary.g_o : GraphLibrary.lhs
GraphLibrary.g_o : ./MyPrelude.g_hi
GraphLibrary.g_o : ./StateFix.g_hi
InferKind.g_o : InferKind.lhs
InferKind.g_o : ./Grammar.g_hi
InferKind.g_o : ./TypeGraph.g_hi
InferKind.g_o : ./TypeBasis.g_hi
InferKind.g_o : ./PrettyPrinter.g_hi
InferKind.g_o : ./UnifyTypes.g_hi
InferKind.g_o : ./MonadLibrary.g_hi
InferType.g_o : InferType.lhs
InferType.g_o : ./InferKind.g_hi
InferType.g_o : ./UnifyTypes.g_hi
InferType.g_o : ./TypeGraph.g_hi
InferType.g_o : ./TypeBasis.g_hi
InferType.g_o : ./StartTBasis.g_hi
InferType.g_o : ./Env.g_hi
InferType.g_o : ./MyPrelude.g_hi
InferType.g_o : ./MonadLibrary.g_hi
InferType.g_o : ./StateFix.g_hi
InferType.g_o : ./Grammar.g_hi
InferType.g_o : ./Folding.g_hi
InferType.g_o : ./ParseLibrary.g_hi
InferType.g_o : ./Parser.g_hi
InferType.g_o : ./PrettyPrinter.g_hi
LabelType.g_o : LabelType.lhs
LabelType.g_o : ./Env.g_hi
LabelType.g_o : ./Folding.g_hi
LabelType.g_o : ./Grammar.g_hi
LabelType.g_o : ./InferType.g_hi
LabelType.g_o : ./MonadLibrary.g_hi
LabelType.g_o : ./MyPrelude.g_hi
LabelType.g_o : ./StartTBasis.g_hi
LabelType.g_o : ./StateFix.g_hi
LabelType.g_o : ./TypeBasis.g_hi
LabelType.g_o : ./TypeGraph.g_hi
LabelType.g_o : ./UnifyTypes.g_hi
Main.g_o : Main.lhs
Main.g_o : ./DependencyAnalysis.g_hi
Main.g_o : ./Env.g_hi
Main.g_o : ./Grammar.g_hi
Main.g_o : ./LabelType.g_hi
Main.g_o : ./MonadLibrary.g_hi
Main.g_o : ./Parser.g_hi
Main.g_o : ./PolyInstance.g_hi
Main.g_o : ./PrettyPrinter.g_hi
Main.g_o : ./StateFix.g_hi
Main.g_o : ./TypeBasis.g_hi
Main.g_o : ./TypeGraph.g_hi
Main.g_o : ./UnifyTypes.g_hi
MonadLibrary.g_o : MonadLibrary.lhs
MonadLibrary.g_o : ./StateFix.g_hi
MonadLibrary.g_o : ./MyPrelude.g_hi
MyPrelude.g_o : MyPrelude.lhs
MyPrelude.g_o : ./NonStdTrace.g_hi
NonStdTrace.g_o : NonStdTrace.lhs
ParseLibrary.g_o : ParseLibrary.lhs
ParseLibrary.g_o : ./MonadLibrary.g_hi
Parser.g_o : Parser.lhs
Parser.g_o : ./MyPrelude.g_hi
Parser.g_o : ./MonadLibrary.g_hi
Parser.g_o : ./ParseLibrary.g_hi
Parser.g_o : ./Grammar.g_hi
PolyInstance.g_o : PolyInstance.lhs
PolyInstance.g_o : ./Env.g_hi
PolyInstance.g_o : ./Grammar.g_hi
PolyInstance.g_o : ./Folding.g_hi
PolyInstance.g_o : ./Functorize.g_hi
PolyInstance.g_o : ./MonadLibrary.g_hi
PolyInstance.g_o : ./MyPrelude.g_hi
PolyInstance.g_o : ./Parser.g_hi
PolyInstance.g_o : ./PrettyPrinter.g_hi
PolyInstance.g_o : ./StartTBasis.g_hi
PolyInstance.g_o : ./TypeBasis.g_hi
PrettyPrintExtra.g_o : PrettyPrintExtra.lhs
PrettyPrintExtra.g_o : ./PrettyPrintLibrary.g_hi
PrettyPrintLibrary.g_o : PrettyPrintLibrary.lhs
PrettyPrinter.g_o : PrettyPrinter.lhs
PrettyPrinter.g_o : ./PrettyPrintExtra.g_hi
PrettyPrinter.g_o : ./Grammar.g_hi
StartTBasis.g_o : StartTBasis.lhs
StartTBasis.g_o : ./Parser.g_hi
StartTBasis.g_o : ./ParseLibrary.g_hi
StartTBasis.g_o : ./MyPrelude.g_hi
StartTBasis.g_o : ./Grammar.g_hi
StartTBasis.g_o : ./MonadLibrary.g_hi
StartTBasis.g_o : ./Env.g_hi
StartTBasis.g_o : ./TypeBasis.g_hi
StateFix.g_o : StateFix.lhs
TypeBasis.g_o : TypeBasis.lhs
TypeBasis.g_o : ./Grammar.g_hi
TypeBasis.g_o : ./Folding.g_hi
TypeBasis.g_o : ./MyPrelude.g_hi
TypeBasis.g_o : ./MonadLibrary.g_hi
TypeBasis.g_o : ./Env.g_hi
TypeBasis.g_o : ./TypeGraph.g_hi
TypeGraph.g_o : TypeGraph.lhs
TypeGraph.g_o : ./MyPrelude.g_hi
TypeGraph.g_o : ./Grammar.g_hi
TypeGraph.g_o : ./PrettyPrinter.g_hi
TypeGraph.g_o : ./MonadLibrary.g_hi
TypeGraph.g_o : ./Env.g_hi
TypeGraph.g_o : ./Folding.g_hi
UnifyTypes.g_o : UnifyTypes.lhs
UnifyTypes.g_o : ./TypeGraph.g_hi
UnifyTypes.g_o : ./MonadLibrary.g_hi
UnifyTypes.g_o : ./Env.g_hi
UnifyTypes.g_o : ./PrettyPrinter.g_hi
UnifyTypes.g_o : ./Grammar.g_hi
UnifyTypes.g_o : ./MyPrelude.g_hi
# DO NOT DELETE: End of Haskell dependencies
